version: '3.4'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
    ports:
      - 8432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    